# This file was generated by GoReleaser. DO NOT EDIT.
class Geocsv < Formula
  desc ""
  homepage ""
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ivy-re-tech/geocsv/releases/download/v0.0.1/geocsv_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "fd41ac5096407522b351c72df88c52fdee0080a38c974e14387664f06b86f1f4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ivy-re-tech/geocsv/releases/download/v0.0.1/geocsv_0.0.1_Linux_x86_64.tar.gz"
      sha256 "5f977bd37c87be719254331c4cdeb34e28b01163d226868fe75b4d6c3047b944"
    end
  end

  def install
    bin.install "geocsv"
  end
end
